# Generated by Django 5.1.7 on 2025-03-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_subcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_des',
            new_name='product_des',
        ),
    ]
