# Generated by Django 5.1.7 on 2025-04-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_order_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address2',
            field=models.CharField(max_length=111),
        ),
        migrations.AlterField(
            model_name='orders',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
